### ISSUE TITLE
Needs a licence

### ISSUE THREAD

**Issue by admiyo** [ainaimi/pgf#1]
Suggest you use and Apache/BSD style license.  Since R is interpreted, this is probablty sufficient to protect end users against proprietary extensions, while still allowing the code to be used in other applications.

GPL would also make sense, though.

https://cran.r-project.org/web/licenses/

**Comment by admiyo** [comment]
Should be covered by

https://github.com/ainaimi/pgf/pull/3

**Comment by ainaimi** [comment]
Thanks, I merged the license to main branch.
