### ISSUE TITLE
Pulls in local code:

### ISSUE THREAD

**Issue by admiyo** [ainaimi/pgf#2]
Can't access the code sourced in via:

source(file="~/Dropbox/Documents/R/ipak.R")

and the dataset assumes a Drop Box file system that probably does not exist, either.

("~/Dropbox/Documents/Research/Papers/EAGeR_GFormula/imputed_eager_monthly_final_03Jan17.txt", sep="\t",header=T)

**Comment by admiyo** [comment]
And this source file as well.  Can all this code be shared as well?

source(file="~/Dropbox/Documents/Research/Papers/EAGeR_GFormula/EAGeRWrapper.R")

**Comment by ainaimi** [comment]
Thanks for bringing to my attention. The most recent commit should resolve these.
