### ISSUE TITLE
aspirin_compliance dataset lacking columns.

### ISSUE THREAD

**Issue by admiyo** [ainaimi/pgf#4]
Is the aspirin_compliance.txt dataset  supposed to run?  Using the code with the below changes got the error

Error in `[.data.frame`(m, , identifier) : undefined columns selected

Made the following changes and ran:

diff --git a/pgf_v0.0.0.9000.R b/pgf_v0.0.0.9000.R
index bda4389..b0c3834 100644
--- a/pgf_v0.0.0.9000.R
+++ b/pgf_v0.0.0.9000.R
@@ -1,14 +1,11 @@
 #################
-rm(list=ls());cat("\014")
-dir<-"~/Dropbox/Documents/Research/Papers/EAGeR_GFormula/"
-setwd(dir)
-
 # load support files
 source(file="ipak.R")
 source(file="SL_Wrapper.R")
-e1<-read.table("Rpgf_dat.txt", sep="\t",header=T)
+e1<-read.table("aspirin_compliance.txt", sep="\t",header=T)
+
 
-# lodad packages
+# load packages
 packages <- c("SuperLearner","data.table","doParallel","doRNG","sampling","plyr","profvis")
 ipak(packages)

 

Got the errors below.

> # create SL library
> SL.library<-c("SL.mean","SL.glm","SL.nnet",
+               "SL.gam.1","SL.gam.2","SL.gam.3","SL.gam.4",
+               "SL.glmnet","SL.glmnet.0.25","SL.glmnet.0.5","SL.glmnet.0.75")
> #################
> 
> # set monte carlo re-sample size
> montecarlo<-1228
> 
> # arrange dataset & create variables
> data_format<-function(data, identifier, timescale){
+   m<-data
+   m$id<-m[,identifier]
+   m$mm<-m[,timescale];m$mm1<-m[,timescale]-1
+   m[,timescale]<-m[,identifier]<-NULL
+   return(m)
+ }
> m<-data_format(e1,"Study_ID","study_month")
Error in `[.data.frame`(m, , identifier) : undefined columns selected
Calls: data_format -> [ -> [.data.frame

**Comment by ainaimi** [comment]
Thanks, most recent commits should fix this.
